### ISSUE TITLE
Error when updating from 0.4 to 0.5?

### ISSUE THREAD

**Issue by githubaccount624** [bikeshedder/deadpool#30]
Hi, I'm updating my app to from 0.4 to 0.5 and I'm getting these errors when building:

```rust
error[E0599]: no method named `host_path` found for type `tokio_postgres::config::Config` in the current scope
   --> C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\deadpool-postgres-0.5.0\src\config.rs:202:17
    |
202 |             cfg.host_path("/run/postgresql");
    |                 ^^^^^^^^^ method not found in `tokio_postgres::config::Config`

error[E0599]: no method named `host_path` found for type `tokio_postgres::config::Config` in the current scope
   --> C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\deadpool-postgres-0.5.0\src\config.rs:204:17
    |
204 |             cfg.host_path("/var/run/postgresql");
    |                 ^^^^^^^^^ method not found in `tokio_postgres::config::Config`

error[E0599]: no method named `host_path` found for type `tokio_postgres::config::Config` in the current scope
   --> C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\deadpool-postgres-0.5.0\src\config.rs:206:17
    |
206 |             cfg.host_path("/tmp");
    |                 ^^^^^^^^^ method not found in `tokio_postgres::config::Config`

error: aborting due to 3 previous errors
```

Any advice for how to solve?

**Comment by bikeshedder** [comment]
I just fixed this in eaebf61b313ae9b0ac7a883c1d8e1d6b1c8bb0b8.

Please give [`deadpool-postgres = "0.5.1"`](https://crates.io/crates/deadpool-postgres/0.5.1) a try. I just released it on `crates.io`.

**Comment by githubaccount624** [comment]
Thanks, it compiles now.
