### ISSUE TITLE
deadpool-diesel async troubles

### ISSUE THREAD

**Issue by mrd0ll4r** [bikeshedder/deadpool#220]
Hello!

I wanted to try this out with the new diesel v2.0 release with Postgres, but came across two issues. First some dependency stuff:

```toml
tokio = { version = "1.20.1", features = ["rt-multi-thread", "net", "sync","macros"] }
anyhow = "1.0.65"

diesel = { version = "2.0.0", features = ["postgres", "chrono"] }
dotenvy = "0.15"
diesel_migrations = "2.0.0"
deadpool-diesel = {version = "0.4.0", features=["postgres"]}

thiserror = "1.0.31"
```

Now the problems:

1) I don't seem to be able to figure out the right error type for `PoolBuilder::build`, which I wanted to use in an error enum via `thiserror`. I figured it was `BuildError`, but the compiler is not happy:
```rust
use deadpool_diesel::postgres::{BuildError, Manager, Pool};
use deadpool_diesel::Runtime;

#[derive(Error, Debug)]
pub enum PoolError {
    #[error("unable to load .env file")]
    Env(dotenvy::Error),
    #[error("missing DATABASE_URL")]
    DatabaseURL,
    #[error("unable to build pool")]
    PoolBuilder(BuildError),
    // This works as a crutch
    #[error("other")]
    Other(Box<dyn std::error::Error + Send + Sync + 'static>)
}

pub fn set_up_pool() -> Result<Pool, PoolError> {
    dotenvy::dotenv().map_err(PoolError::Env)?;
    let database_url = env::var("DATABASE_URL").map_err(|_| PoolError::DatabaseURL)?;

    let manager = Manager::new(database_url, Runtime::Tokio1);

    let pool = Pool::builder(manager)
        .max_size(8)
        .build()
        .map_err(|e| PoolError::PoolBuilder(e))?;

    Ok(pool)
}
```
with this error:
```
error[E0308]: mismatched types
  --> src/lib.rs:54:53
   |
54 |         .build().map_err(|e| PoolError::PoolBuilder(e))?;
   |                              ---------------------- ^ expected enum `diesel::ConnectionError`, found enum `deadpool_diesel::Error`
   |                              |
   |                              arguments to this enum variant are incorrect
   |
   = note: expected enum `deadpool::managed::builder::BuildError<diesel::ConnectionError>`
              found enum `deadpool::managed::builder::BuildError<deadpool_diesel::Error>`
note: tuple variant defined here
  --> src/lib.rs:41:5
   |
41 |     PoolBuilder(BuildError),
   |     ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
```
I looked through the source and various type aliases for a while, but I'm thorougly confused, sorry...

2) If I have a pool, whenever I use a connection from within `tokio::main`, the compiler complains about `InteractError` not being `Sync` (I think):
```rust

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // Open DB connection
    let pool = set_up_pool()
        .context("unable to set up connection pool")?;

    let conn = pool.get().await.context("unable to get a connection")?;
    let result = conn.interact(|conn| {
        do_stuff(conn)
    }).await??;
}

pub fn do_stuff(
    conn: &mut PgConnection,
) -> Result<SomeSimpleEnum, diesel::result::Error> {...}
```
with this intimidating message:
```
error[E0277]: `(dyn Any + Send + 'static)` cannot be shared between threads safely
  --> src/bin/do-stuff.rs:32:13
   |
32 |     }).await??;
   |             ^ `(dyn Any + Send + 'static)` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `(dyn Any + Send + 'static)`
   = help: the following other types implement trait `FromResidual<R>`:
             <Result<T, F> as FromResidual<Result<Infallible, E>>>
             <Result<T, F> as FromResidual<Yeet<E>>>
   = note: required because of the requirements on the impl of `Sync` for `Unique<(dyn Any + Send + 'static)>`
   = note: required because it appears within the type `Box<(dyn Any + Send + 'static)>`
   = note: required because it appears within the type `deadpool_sync::InteractError`
   = note: required because of the requirements on the impl of `From<deadpool_sync::InteractError>` for `anyhow::Error`
   = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, deadpool_sync::InteractError>>` for `Result<(), anyhow::Error>`

For more information about this error, try `rustc --explain E0277`.
```

I feel like I'm making some basic mistake somewhere, but I haven't figured it out after a few hours, so I thought I might ask...

**Comment by bikeshedder** [comment]
1. I can't reproduce this. When copying your code 1:1 it compiles just fine. :see_no_evil: 
2. `InteractError` is not `Sync` and therefore incompatible with `anyhow` as it seams to require all errors to be `Sync`. I wonder why that is and in order to fix this your best chance is to replace the `?` by a custom `.map_err(...)` call, `.unwrap()` call or don't use `anyhow::Result' and remove the `Sync` trait from the `Other` enum variant.

I just talked to @Darksonn on the [tokio discord](https://discord.com/channels/500028886025895936/500336333500448798/1022180231274053664) about that and it seams that the most ergonomic choice for users would be if `InteractError` was `+ Sync` too. This would require `InteractError::Panic` to become a `struct` with methods similar to [tokio::task::JoinError](https://docs.rs/tokio/latest/tokio/task/struct.JoinError.html)

**Comment by bikeshedder** [comment]
I just found the following text in the [documentation of `anyhow`](https://docs.rs/anyhow/1.0.65/anyhow/struct.Error.html)
> `Error` requires that the error is `Send`, `Sync`, and `'static`.

Right now the `InteractError` is not `Sync` and therefore incompatible with `anyhow`.

@dtolnay Why does `anyhow::Error` require the error to be `Sync`? Is there maybe a better way to handle that panic with `anyhow`?

**Comment by mrd0ll4r** [comment]
Thanks for looking into this!
Re 1: I put together a non-compiling MVP here: https://github.com/mrd0ll4r/deadpool_error_issue

I'm on `rustc 1.63.0 (4b91a6ea7 2022-08-08)`.

`cargo check` after `cargo clean`:
```
$ cargo check
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.100
   Compiling autocfg v1.1.0
   Compiling libc v0.2.133
   Compiling version_check v0.9.4
   Compiling serde_derive v1.0.144
   Compiling serde v1.0.144
   Compiling log v0.4.17
    Checking cfg-if v1.0.0
    Checking once_cell v1.15.0
   Compiling pq-sys v0.4.7
    Checking pin-project-lite v0.2.9
   Compiling async-trait v0.1.57
    Checking iana-time-zone v0.1.48
    Checking byteorder v1.4.3
    Checking retain_mut v0.1.9
    Checking bitflags v1.3.2
    Checking itoa v1.0.3
   Compiling thiserror v1.0.35
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling num-traits v0.2.15
   Compiling tokio v1.21.1
   Compiling num-integer v0.1.45
    Checking num_cpus v1.13.1
    Checking socket2 v0.4.7
    Checking mio v0.8.4
    Checking dirs-sys v0.3.7
    Checking dirs v4.0.0
    Checking dotenvy v0.15.5
    Checking chrono v0.4.22
   Compiling tokio-macros v1.8.0
   Compiling diesel_derives v2.0.0
   Compiling thiserror-impl v1.0.35
    Checking deadpool-runtime v0.1.2
    Checking deadpool v0.9.5
    Checking diesel v2.0.0
    Checking deadpool-sync v0.1.0
    Checking toml v0.5.9
    Checking migrations_internals v2.0.0
   Compiling migrations_macros v2.0.0
    Checking diesel_migrations v2.0.0
    Checking deadpool-diesel v0.4.0
    Checking deadpool_error_issue v0.1.0 (/mnt/e/projects/x/deadpool_error_issue)
error[E0308]: mismatched types
  --> src/lib.rs:31:45
   |
31 |         .map_err(|e| PoolError::PoolBuilder(e))?;
   |                      ---------------------- ^ expected enum `diesel::result::ConnectionError`, found enum `deadpool_diesel::Error`
   |                      |
   |                      arguments to this enum variant are incorrect
   |
   = note: expected enum `deadpool::managed::builder::BuildError<diesel::result::ConnectionError>`
              found enum `deadpool::managed::builder::BuildError<deadpool_diesel::Error>`
note: tuple variant defined here
  --> src/lib.rs:18:5
   |
18 |     PoolBuilder(BuildError),
   |     ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `deadpool_error_issue` due to previous error
```

Does that compile for you?

**Comment by bikeshedder** [comment]
Oh. I've tested your code against my local checkout where I'm working on the 0.10 milestone.

I did remove the generic from the `BuildError` which was unused anyways. That explains why I was unable to reproduce the first error. :facepalm: 

See https://github.com/bikeshedder/deadpool/tree/milestone/v0.10

It seams that the `BuildError` re-export is of the wrong type. Nobody ever used that re-export so it never got noticed by anyone before. Good catch!

For the time being you could use the `deadpool::managed::BuildError<deadpool_diesel::Error>` type directly rather than relying on the wrong re-export.

I'll try to find some time to make [`0.10`](https://github.com/bikeshedder/deadpool/milestone/4) happen over the weekend. It's mainly refactoring and includes most of the **quality of life** changes.

**Comment by bikeshedder** [comment]
The milestone branch is now merged to the main branch which fixes this issue.
